CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKENS
(
    TOKEN_ID SERIAL NOT NULL
        CONSTRAINT RESET_PASSWORD_TOKENS_PKEY
        PRIMARY KEY,
    TOKEN VARCHAR,
    USER_ID INTEGER
        CONSTRAINT RESET_PASSWORD_TOKENS_USER_ID_FKEY
        REFERENCES USERS,
    DATE_EXPIRATION TIMESTAMP
);