ALTER TABLE POSTS
    ADD COLUMN FOREIGN_EXPERT_ID INTEGER
        CONSTRAINT POSTS_FOREIGN_EXPERT_ID_FKEY
            REFERENCES FOREIGN_EXPERTS;

-- This index is done to speed up filtering posts by foreign expert IDs
CREATE INDEX POSTS_FOREIGN_EXPERT_ID_IDX
    ON POSTS (FOREIGN_EXPERT_ID);