ALTER TABLE PUBLIC.USERS
    DROP COLUMN PROVIDER;
ALTER TABLE PUBLIC.USERS
    DROP COLUMN PROVIDER_ID;

CREATE TABLE PUBLIC.PROVIDERS
(
    PROVIDER_ID         SERIAL PRIMARY KEY,
    PROVIDER_NAME       VARCHAR,
    EMAIL               VARCHAR,
    USER_ID_BY_PROVIDER VARCHAR,
    USER_ID             INT,
    FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (user_id)
);
