insert into PUBLIC.PROVIDERS (PROVIDER_NAME,EMAIL,USER_ID_BY_PROVIDER,USER_ID) VALUES ('LOCAL','qwerty@gmail.com','123123',38);
insert into PUBLIC.PROVIDERS (PROVIDER_NAME,EMAIL,USER_ID_BY_PROVIDER,USER_ID) VALUES ('LOCAL','oleh@mail.com','123123',6);
insert into PUBLIC.PROVIDERS (PROVIDER_NAME,EMAIL,USER_ID_BY_PROVIDER,USER_ID) VALUES ('LOCAL','admin@mail.com','123123',9);
