create table flyway_schema_history
(
	installed_rank integer not null
		constraint flyway_schema_history_pk
			primary key,
	version varchar(50),
	description varchar(200) not null,
	type varchar(20) not null,
	script varchar(1000) not null,
	checksum integer,
	installed_by varchar(100) not null,
	installed_on timestamp default now() not null,
	execution_time integer not null,
	success boolean not null
);

alter table flyway_schema_history owner to postgres;

create index flyway_schema_history_s_idx
	on flyway_schema_history (success);

create table roles
(
	role_id serial not null
		constraint roles_pkey
			primary key,
	role_name varchar
);

alter table roles owner to postgres;

create table users
(
	user_id serial not null
		constraint users_pkey
			primary key,
	email varchar,
	password varchar,
	status varchar,
	first_name varchar,
	last_name varchar,
	phone varchar,
	created_at timestamp default now(),
	avatar varchar,
	enabled boolean,
	role_id integer
		constraint users_role_id_fkey
			references roles
);

alter table users owner to postgres;

create table regions
(
	region_id serial not null
		constraint regions_pkey
			primary key,
	name varchar
);

alter table regions owner to postgres;

create table tags
(
	tag_id serial not null
		constraint tags_pkey
			primary key,
	tag varchar
		constraint unique_name
			unique
);

alter table tags owner to postgres;

create table charities
(
	charity_id serial not null
		constraint charities_pkey
			primary key,
	body text,
	author_id integer
		constraint charities_author_id_fkey
			references users,
	created_at timestamp default now(),
	modified_at timestamp default now()
);

alter table charities owner to postgres;

create table sources
(
	source_id serial not null
		constraint sources_pkey
			primary key,
	type varchar,
	value varchar,
	user_id integer
		constraint sources_user_id_fkey
			references users
);

alter table sources owner to postgres;

create table directions
(
	direction_id serial not null
		constraint directions_pkey
			primary key,
	label varchar,
	color varchar(7) default NULL::character varying,
	name varchar
);

alter table directions owner to postgres;

create table post_types
(
	type_id serial not null
		constraint post_types_pkey
			primary key,
	name varchar
);

alter table post_types owner to postgres;

create table posts
(
	post_id serial not null
		constraint posts_pkey
			primary key,
	author_id integer
		constraint posts_author_id_fkey
			references users,
	type_id integer
		constraint posts_type_id_fkey
			references post_types,
	title varchar,
	content text,
	status varchar,
	important boolean,
	created_at timestamp default now(),
	modified_at timestamp default now(),
	preview text
);

alter table posts owner to postgres;

create table posts_tags
(
	post_id integer
		constraint posts_tags_post_id_fkey
			references posts,
	tag_id integer
		constraint posts_tags_tag_id_fkey
			references tags
);

alter table posts_tags owner to postgres;

create table posts_sources
(
	post_id integer
		constraint posts_sources_post_id_fkey
			references posts,
	source_id integer
		constraint posts_sources_source_id_fkey
			references sources
);

alter table posts_sources owner to postgres;

create table posts_directions
(
	post_id integer
		constraint posts_directions_post_id_fkey
			references posts,
	direction_id integer
		constraint posts_directions_direction_id_fkey
			references directions
);

alter table posts_directions owner to postgres;

create table cities
(
	city_id integer generated by default as identity
		constraint cities_pkey
			primary key,
	name varchar(255),
	region_id integer
		constraint cities_region_id_fkey
			references regions
);

alter table cities owner to postgres;

create table institutions
(
	institution_id serial not null
		constraint institutions_pkey
			primary key,
	name varchar,
	address varchar,
	city_id integer
		constraint institutions_city_id_fkey
			references cities
);

alter table institutions owner to postgres;

create table verification_tokens
(
	id serial not null
		constraint verification_tokens_pkey
			primary key,
	token varchar,
	user_id integer
		constraint verification_tokens_user_id_fkey
			references users
);

alter table verification_tokens owner to postgres;

create table providers
(
	provider_id serial not null
		constraint providers_pkey
			primary key,
	provider_name varchar,
	email varchar,
	user_id_by_provider varchar,
	user_id integer
		constraint providers_user_id_fkey
			references users
);

alter table providers owner to postgres;

create table doctors
(
	doctor_id serial not null
		constraint doctors_pkey
			primary key,
	qualification varchar,
	bio varchar,
	user_id integer
		constraint doctors_user_id_fkey
			references users,
	institution_id integer
		constraint doctors_institution_id_fkey
			references institutions,
	promotion_scale real default 1.0,
	promotion_level integer default 0,
	published_posts bigint default 0,
	rating bigint default 0
);

alter table doctors owner to postgres;

create table doctors_institutions
(
	doctor_id integer
		constraint doctors_institutions_doctor_id_fkey
			references doctors,
	institution_id integer
		constraint doctors_institutions_institution_id_fkey
			references institutions
);

alter table doctors_institutions owner to postgres;

create table doctors_directions
(
	doctor_id integer
		constraint doctors_directions_doctor_id_fkey
			references doctors,
	direction_id integer
		constraint doctors_directions_direction_id_fkey
			references directions
);

alter table doctors_directions owner to postgres;

create table role_permission
(
	role_id integer
		constraint role_id_role_id_fk
			references roles,
	permissions varchar
);

alter table role_permission owner to postgres;