SET STATEMENT_TIMEOUT = 0;
SET LOCK_TIMEOUT = 0;
SET IDLE_IN_TRANSACTION_SESSION_TIMEOUT = 0;
SET CLIENT_ENCODING = 'UTF8';
SET STANDARD_CONFORMING_STRINGS = ON;
SELECT PG_CATALOG.SET_CONFIG('SEARCH_PATH', '', FALSE);
SET CHECK_FUNCTION_BODIES = FALSE;
SET XMLOPTION = CONTENT;
SET CLIENT_MIN_MESSAGES = WARNING;
SET ROW_SECURITY = OFF;

SET DEFAULT_TABLESPACE = '';

SET DEFAULT_TABLE_ACCESS_METHOD = HEAP;

CREATE TABLE PUBLIC.USERS (
  USER_ID SERIAL PRIMARY KEY,
  EMAIL VARCHAR,
  PASSWORD VARCHAR,
  STATUS VARCHAR,
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  QUALIFICATION VARCHAR,
  PHONE VARCHAR,
  BIO TEXT,
  CREATED_AT TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE PUBLIC.ROLES (
  ROLE_ID SERIAL PRIMARY KEY,
  ROLE_NAME VARCHAR
);

CREATE TABLE PUBLIC.ROLES_USERS (
  ROLE_ID INT,
  USER_ID INT
);

CREATE TABLE PUBLIC.REGIONS (
  REGION_ID SERIAL PRIMARY KEY,
  NAME VARCHAR
);

CREATE TABLE PUBLIC.INSTITUTIONS (
  INSTITUTION_ID SERIAL PRIMARY KEY,
  NAME VARCHAR,
  REGION_ID INT,
  ADDRESS VARCHAR
);

CREATE TABLE PUBLIC.USERS_INSTITUTIONS (
  USER_ID INT,
  INSTITUTION_ID INT,
  IS_PRIMARY BOOLEAN
);

CREATE TABLE PUBLIC.TAGS (
  TAG_ID SERIAL PRIMARY KEY,
  TAG VARCHAR
);

CREATE TABLE PUBLIC.POSTS_TAGS (
  POST_ID INT,
  TAG_ID INT
);

CREATE TABLE PUBLIC.POSTS (
  POST_ID SERIAL PRIMARY KEY,
  AUTHOR_ID INT,
  DIRECTION_ID INT,
  TYPE_ID INT,
  TITLE VARCHAR,
  CONTENT TEXT,
  STATUS VARCHAR,
  IMPORTANT BOOLEAN,
  TAGS VARCHAR,
  CREATED_AT TIMESTAMP DEFAULT (NOW()),
  MODIFIED_AT TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE PUBLIC.CHARITIES (
  CHARITY_ID SERIAL PRIMARY KEY,
  BODY TEXT,
  AUTHOR_ID INT,
  CREATED_AT TIMESTAMP DEFAULT (NOW()),
  MODIFIED_AT TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE PUBLIC.SOURCES (
  SOURCE_ID SERIAL PRIMARY KEY,
  TYPE VARCHAR,
  VALUE VARCHAR
);

CREATE TABLE PUBLIC.USERS_SOURCES (
  USER_ID INT,
  SOURCE_ID INT
);

CREATE TABLE PUBLIC.POSTS_SOURCES (
  POST_ID INT,
  SOURCE_ID INT
);

CREATE TABLE PUBLIC.USERS_DIRECTIONS (
  USER_ID INT,
  DIRECTION_ID INT
);

CREATE TABLE PUBLIC.DIRECTIONS (
  DIRECTION_ID SERIAL PRIMARY KEY,
  NAME VARCHAR
);

CREATE TABLE PUBLIC.POSTS_DIRECTIONS (
  POST_ID INT,
  DIRECTION_ID INT
);

CREATE TABLE PUBLIC.POST_TYPES (
  TYPE_ID SERIAL PRIMARY KEY,
  NAME VARCHAR
);

ALTER TABLE PUBLIC.ROLES_USERS ADD FOREIGN KEY (ROLE_ID) REFERENCES PUBLIC.ROLES(ROLE_ID);

ALTER TABLE PUBLIC.ROLES_USERS ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID);

ALTER TABLE PUBLIC.INSTITUTIONS ADD FOREIGN KEY (REGION_ID) REFERENCES PUBLIC.REGIONS(REGION_ID);

ALTER TABLE PUBLIC.USERS_INSTITUTIONS ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.USERS_INSTITUTIONS ADD FOREIGN KEY (INSTITUTION_ID) REFERENCES PUBLIC.INSTITUTIONS (INSTITUTION_ID);

ALTER TABLE PUBLIC.POSTS_TAGS ADD FOREIGN KEY (POST_ID) REFERENCES PUBLIC.POSTS (POST_ID);

ALTER TABLE PUBLIC.POSTS_TAGS ADD FOREIGN KEY (TAG_ID) REFERENCES PUBLIC.TAGS (TAG_ID);

ALTER TABLE PUBLIC.POSTS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.POSTS ADD FOREIGN KEY (TYPE_ID) REFERENCES PUBLIC.POST_TYPES (TYPE_ID);

ALTER TABLE PUBLIC.CHARITIES ADD FOREIGN KEY (AUTHOR_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.USERS_SOURCES ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.USERS_SOURCES ADD FOREIGN KEY (SOURCE_ID) REFERENCES PUBLIC.SOURCES (SOURCE_ID);

ALTER TABLE PUBLIC.POSTS_SOURCES ADD FOREIGN KEY (POST_ID) REFERENCES PUBLIC.POSTS (POST_ID);

ALTER TABLE PUBLIC.POSTS_SOURCES ADD FOREIGN KEY (SOURCE_ID) REFERENCES PUBLIC.SOURCES (SOURCE_ID);

ALTER TABLE PUBLIC.USERS_DIRECTIONS ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.USERS_DIRECTIONS ADD FOREIGN KEY (DIRECTION_ID) REFERENCES PUBLIC.DIRECTIONS (DIRECTION_ID);

ALTER TABLE PUBLIC.POSTS_DIRECTIONS ADD FOREIGN KEY (POST_ID) REFERENCES PUBLIC.POSTS (POST_ID);

ALTER TABLE PUBLIC.POSTS_DIRECTIONS ADD FOREIGN KEY (DIRECTION_ID) REFERENCES PUBLIC.DIRECTIONS (DIRECTION_ID);