ALTER TABLE PUBLIC.USERS DROP COLUMN QUALIFICATION;

ALTER TABLE PUBLIC.USERS DROP COLUMN BIO;

ALTER TABLE PUBLIC.USERS DROP COLUMN PROMOTION_SCALE;

ALTER TABLE PUBLIC.USERS DROP COLUMN PROMOTION_LEVEL;

ALTER TABLE PUBLIC.USERS DROP COLUMN INSTITUTION_ID CASCADE;

DROP TABLE PUBLIC.USERS_INSTITUTIONS CASCADE;

DROP TABLE PUBLIC.USERS_DIRECTIONS CASCADE;

CREATE TABLE PUBLIC.DOCTORS (
    DOCTOR_ID SERIAL PRIMARY KEY,
    QUALIFICATION VARCHAR,
    BIO VARCHAR,
    USER_ID INT,
    INSTITUTION_ID INT,
    PROMOTION_SCALE REAL DEFAULT (1.0),
    PROMOTION_LEVEL INT DEFAULT (0)
);

CREATE TABLE PUBLIC.DOCTORS_INSTITUTIONS (
    DOCTOR_ID INT,
    INSTITUTION_ID INT
);

CREATE TABLE PUBLIC.DOCTORS_DIRECTIONS (
    DOCTOR_ID INT,
    DIRECTION_ID INT
);

ALTER TABLE PUBLIC.DOCTORS ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.DOCTORS ADD FOREIGN KEY (INSTITUTION_ID) REFERENCES PUBLIC.INSTITUTIONS (INSTITUTION_ID);

ALTER TABLE PUBLIC.DOCTORS_INSTITUTIONS ADD FOREIGN KEY (DOCTOR_ID) REFERENCES PUBLIC.DOCTORS (DOCTOR_ID);

ALTER TABLE PUBLIC.DOCTORS_INSTITUTIONS ADD FOREIGN KEY (INSTITUTION_ID) REFERENCES PUBLIC.INSTITUTIONS (INSTITUTION_ID);

ALTER TABLE PUBLIC.DOCTORS_DIRECTIONS ADD FOREIGN KEY (DOCTOR_ID) REFERENCES PUBLIC.DOCTORS (DOCTOR_ID);

ALTER TABLE PUBLIC.DOCTORS_DIRECTIONS ADD FOREIGN KEY (DIRECTION_ID) REFERENCES PUBLIC.DIRECTIONS (DIRECTION_ID);