drop table users_sources;

alter table if exists sources add column user_id int;
alter table if exists sources add constraint sources_user_id_fkey foreign key (user_id) references users;

create table cities (
    city_id int4 generated by default as identity,
    name varchar(255), region_id int,
    primary key (city_id));
alter table if exists cities add constraint cities_region_id_fkey foreign key (region_id) references regions;

alter table if exists institutions drop constraint institutions_region_id_fkey;
alter table if exists institutions drop column region_id;
alter table if exists institutions add column city_id int;
alter table if exists institutions add constraint institutions_city_id_fkey foreign key (city_id) references cities;