ALTER TABLE PUBLIC.USERS
    ADD COLUMN PROVIDER VARCHAR;
ALTER TABLE PUBLIC.USERS
    ADD COLUMN PROVIDER_ID VARCHAR;
ALTER TABLE PUBLIC.USERS
    DROP COLUMN AVATAR;
ALTER TABLE PUBLIC.USERS
    ADD AVATAR VARCHAR;
